INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1, 				'ACTIVO', 											1, 0, 'ACTIVO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 101, 				'ACTIVO CORRIENTE', 								2, 1, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10101, 			'DISPONIBLE', 										3, 101, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010101, 		'CAJA', 												4, 10101, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010101001, 	'CAJA M/N', 										5, 1010101, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010101002, 	'CAJA M/E', 										5, 1010101, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010102, 		'BANCOS', 											4, 10101, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010102001, 	'BANCO M/N', 										5, 1010102, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010102002, 	'BANCO M/E', 										5, 1010102, 'ACTIVO', 'EFECTIVO' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10102, 			'EXIGIBLE', 										3, 101, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010201, 		'CUENTAS POR COBRAR', 							4, 10102, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010201001, 	'CUENTAS POR COBRAR', 							5, 1010201, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010202, 		'IMPUESTOS ANTICIPADOS', 						4, 10102, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010202001, 	'CREDITO FISCAL IVA', 							5, 1010202, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010202002, 	'IUE POR COMPENSAR', 							5, 1010202, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10103, 			'REALIZABLE', 										3, 101, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010301, 		'INVENTARIOS', 									4, 10103, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010301001, 	'INVENTARIOS', 									5, 1010301, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10104, 			'GASTOS ANTICIPADOS', 							3, 101, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010401, 		'GASTOS ANTICIPADOS', 							4, 10104, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010401001, 	'ALQUILERES PAGADOS POR ADELANTADO', 		5, 1010401, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010401002, 	'PUBLICIDAD PAGADOS POR ADELANTADO', 		5, 1010401, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10105, 			'INVERSIONES', 									3, 101, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010501, 		'INVERSIONES RAPIDAS', 							4, 10105, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010501001, 	'BONOS COTIZABLES EN LA BOLSA', 				5, 1010501, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1010501002, 	'ACCIONES COTIZABLES EN LA BOLSA', 			5, 1010501, 'ACTIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 102, 				'ACTIVO NO CORRIENTE', 							2, 1, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10201, 			'ACTIVO FIJO', 									3, 102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020101, 		'EDIFICIOS', 										4, 10201, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020101001, 	'EDIFICIOS', 										5, 1020101, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020102, 		'VEHICULOS', 										4, 10201, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020102001, 	'VEHICULOS', 										5, 1020102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020103, 		'MUEBLES Y ENSERES', 							4, 10201, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020103001, 	'MUEBLES Y ENSERES', 							5, 1020103, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020104, 		'EQUIPO DE COMPUTACION', 						4, 10201, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020104001, 	'EQUIPO DE COMPUTACION', 						5, 1020104, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020105, 		'TERRENOS', 										4, 10201, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020105001, 	'TERRENOS', 										5, 1020105, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10202, 			'DEPRE. ACUM. ACTIVO FIJO', 					3, 102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020201, 		'DEPRE. ACUM. EDIFICIOS', 						4, 10202, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020201001, 	'DEPRE. ACUM. EDIFICIOS', 						5, 1020201, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020202, 		'DEPRE. ACUM. VEHICULOS', 						4, 10202, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020202001, 	'DEPRE. ACUM. VEHICULOS', 						5, 1020202, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020203, 		'DEPRE. ACUM. MUEBLES Y ENSERES', 			4, 10202, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020203001, 	'DEPRE. ACUM. MUEBLES Y ENSERES', 			5, 1020203, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020204, 		'DEPRE. ACUM. EQUIPO DE COMPUTACION', 		4, 10202, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020204001, 	'DEPRE. ACUM. EQUIPO DE COMPUTACION', 		5, 1020204, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10203, 			'INTANGIBLE', 										3, 102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020301, 		'PATENTES', 										4, 10203, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020301001, 	'PATENTES', 										5, 1020301, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10204, 			'DIFERIDO', 										3, 102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020401, 		'SEGUROS PAGADOS POR ADELANTADO', 			4, 10204, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020401001, 	'SEGUROS PAGADOS POR ADELANTADO', 			5, 1020401, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020402, 		'GASTOS DE ORGANIZACION Y CONSTITUCION', 	4, 10204, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020402001, 	'GASTOS DE ORGANIZACION Y CONSTITUCION', 	5, 1020402, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10205, 			'INVERSIONES', 									3, 102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020501, 		'INVERSIONES A LARGO PLAZO', 					4, 10205, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020501001, 	'PARTICIPACIONES', 								5, 1020501, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020501002, 	'BONOS TGN', 										5, 1020501, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020501003, 	'TERRENOS PARA FUTURA CONSTRUCCION', 		5, 1020501, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 10206, 			'OTROS ACTIVOS', 									3, 102, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020601, 		'OTROS ACTIVOS', 									4, 10206, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 1020601001, 	'OTROS ACTIVOS', 									5, 1020601, 'ACTIVO', 'INVERSION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2, 				'PASIVO', 											1, 0, 'PASIVO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 201, 				'PASIVO CORRIENTE', 								2, 2, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 20101, 			'DEUDAS COMERCIALES', 							3, 201, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010101, 		'CUENTAS POR PAGAR', 							4, 20101, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010101001, 	'CUENTAS POR PAGAR', 							5, 2010101, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 20102, 			'DEUDAS FISCALES', 								3, 201, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010201, 		'OBLIGACIONES TRIBUTARIAS', 					4, 20102, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010201001, 	'DEBITO FISCAL IVA', 							5, 2010201, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010201002, 	'IMPUESTOS A LAS TRANS. POR PAGAR', 		5, 2010201, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010201003, 	'IUE POR PAGAR', 									5, 2010201, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 20103, 			'DEUDAS SOCIALES', 								3, 201, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010301, 		'OBLIGACIONES CON EL PERSONAL', 				4, 20103, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010301001, 	'SUELDOS Y SALARIOS POR PAGAR', 				5, 2010301, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010301002, 	'AGUINALDOS POR PAGAR', 						5, 2010301, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010302, 		'APORTES LABORALES POR PAGAR', 				4, 20103, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010302001, 	'CUENTA INDIVIDUAL A.F.P. POR PAGAR', 		5, 2010302, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010302002, 	'RIESGO COMUN POR PAGAR', 						5, 2010302, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010302003, 	'COMISION A.F.P. POR PAGAR', 					5, 2010302, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010302004, 	'APORTE LABORAL SOLIDARIO POR PAGAR', 		5, 2010302, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010303, 		'APORTES PATRONALES POR PAGAR', 				4, 20103, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010303001, 	'CAJA NACIONAL DE SALUD POR PAGAR', 		5, 2010303, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010303002, 	'RIESGO PROFESIONAL POR PAGAR', 				5, 2010303, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010303003, 	'PRO VIVIENDA POR PAGAR', 						5, 2010303, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2010303004, 	'APORTE PATRONAL SOLIDARIO POR PAGAR', 	5, 2010303, 'PASIVO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 202, 				'PASIVO NO CORRIENTE', 							2, 2, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 20201, 			'DEUDAS A LARGO PLAZO', 						3, 202, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2020101, 		'DEUDAS BANCARIAS', 								4, 20201, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2020101001, 	'PRESTAMOS BANCARIOS', 							5, 2020101, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2020101002, 	'CREDITOS HIPOTECARIOS', 						5, 2020101, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 20202, 			'RESERVAS Y PROVISIONES', 						3, 202, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2020201, 		'PREVISIONES', 									4, 20202, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 2020201001, 	'PREVISIONES PARA INDEMNIZACION', 			5, 2020201, 'PASIVO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3, 				'PATRIMONIO', 										1, 0, 'PATRIMONIO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 301, 				'PATRIMONIO NETO', 								2, 3, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 30101, 			'CAPITAL', 											3, 301, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010101, 		'CAPITAL SOCIAL', 								4, 30101, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010101001, 	'CAPITAL SOCIAL', 								5, 3010101, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010102, 		'AJUSTE DE CAPITAL', 							4, 30101, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010102001, 	'AJUSTE DE CAPITAL', 							5, 3010102, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 30102, 			'RESERVAS', 										3, 301, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010201, 		'RESERVAS PATRIMONIALES', 						4, 30102, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010201001, 	'RESERVAS PATRIMONIALES', 						5, 3010201, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010202, 		'AJUSTES DE RESERVAS PATRIMONIALES', 		4, 30102, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010202001, 	'AJUSTES DE RESERVAS PATRIMONIALES', 		5, 3010202, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 30103, 			'RESULTADOS', 										3, 301, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010301,			'RESULTADOS ACUMULADOS', 						4, 30103, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010301001, 	'RESULTADOS ACUMULADOS', 						5, 3010301, 'PATRIMONIO', 'FINANCIACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010302, 		'RESULTADOS DE LA GESTION', 					4, 30103, 'PATRIMONIO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 3010302001, 	'RESULTADOS DE LA GESTION', 					5, 3010302, 'PATRIMONIO', 'OPERACION' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4, 				'INGRESO', 											1, 0, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 401, 				'INGRESOS', 										2, 4, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 40101, 			'INGRESOS ORDINARIOS', 							3, 401, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4010101, 		'VENTAS NETAS', 									4, 40101, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4010101001, 	'VENTAS', 											5, 4010101, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4010101002, 	'DESCUENTOS SOBRE VENTAS', 					5, 4010101, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 402, 				'OTROS INGRESOS', 								2, 4, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 40201, 			'INGRESOS NO OPERATIVOS', 						3, 402, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4020101, 		'INGRESOS NO MONETARIOS', 						4, 40201, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4020101001, 	'AJUSTE POR INFLACION Y TENENCIA DE BIENES', 5, 4020101, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 403, 				'INGRESOS FINANCIEROS', 						2, 4, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 40301, 			'INGRESOS FINANCIEROS', 						3, 403, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4030101, 		'INTERESES', 										4, 40301, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 4030101001, 	'INTERESES BANCARIOS', 							5, 4030101, 'INGRESO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5, 				'GASTO', 											1, 0, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 501, 				'COSTOS', 											2, 5, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 50101, 			'COSTOS DE VENTAS', 								3, 501, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5010101, 		'COSTOS DE VENTAS', 								4, 50101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5010101001, 	'COSTOS DE VENTAS', 								5, 5010101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5010102, 		'COMPRAS NETAS', 									4, 50101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5010102001, 	'COMPRAS', 											5, 5010102, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5010102002, 	'DESCUENTO SOBRE COMPRAS', 					5, 5010102, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 502, 				'GASTOS OPERATIVOS', 							2, 5, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 50201, 			'GASTOS DE OPERACION', 							3, 502, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020101, 		'SERVICIOS PROFESIONALES', 					4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020101001, 	'SUELDOS Y SALARIOS', 							5, 5020101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020101002, 	'HONORARIOS PROFESIONALES', 					5, 5020101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020102, 		'CARGAS SOCIALES', 								4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020102001, 	'CARGAS SOCIALES', 								5, 5020102, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020102002, 	'AGUINALDO', 										5, 5020102, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020102003, 	'INDEMNIZACION', 									5, 5020102, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020103, 		'SERVICIOS BASICOS', 							4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020103001, 	'ENERGIA ELECTRICA', 							5, 5020103, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020103002, 	'AGUA Y ALCANTARILLADO', 						5, 5020103, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020103003, 	'SERVICIOS TELEFONICOS', 						5, 5020103, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020104, 		'GASTOS ADMINISTRATIVOS', 						4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020104001, 	'GASTOS GENERALES', 								5, 5020104, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020104002, 	'MATERIAL DE ESCRITORIO', 						5, 5020104, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020105, 		'IMPOSITIVOS', 									4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020105001, 	'IMPUESTOS A LAS TRANSACCIONES', 			5, 5020105, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020106, 		'MANTENIMIENTO DE VALOR', 						4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020106001, 	'MANTENIMIENTO DE VALOR', 						5, 5020106, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020106002, 	'DIFERENCIA DE CAMBIO', 						5, 5020106, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020107, 		'DEPRECIACIONES', 								4, 50201, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020107001, 	'DEPRECIACION EDIFICIOS', 						5, 5020107, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020107002, 	'DEPRECIACION VEHICULOS', 						5, 5020107, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020107003, 	'DEPRECIACION MUEBLES Y ENSERES', 			5, 5020107, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5020107004, 	'DEPRECIACION EQUIPO DE COMPUTACION', 		5, 5020107, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 503, 				'OTROS GASTOS', 									2, 5, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 50301, 			'GASTOS NO OPERATIVOS', 						3, 503, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5030101, 		'GASTOS NO MONETARIOS', 						4, 50301, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5030101001, 	'AJUSTE POR INFLACION Y TENENCIA DE BIENES ',5, 5030101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 504, 				'GASTOS FINANCIEROS', 							2, 5, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 50401, 			'GASTOS FINANCIEROS', 							3, 504, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5040101, 		'INTERESES PAGADOS', 							4, 50401, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5040101001, 	'INTERESES PAGADOS POR PRESTAMOS', 			5, 5040101, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 505, 				'IMPUESTO SOBRE LAS UTILIDADES', 			2, 5, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 50501, 			'IMPUESTO SOBRE LAS UTILIDADES', 			3, 505, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5050101, 		'IMPUESTO SOBRE LAS UTILIDADES', 			4, 50501, 'GASTO', 'N/A' ); 
INSERT INTO plan(  codigoplan, cuenta, nivel, padre, tipo, clase ) VALUES ( 5050101001, 	'IMPUESTO SOBRE LAS UTILIDADES', 			5, 5050101, 'GASTO', 'N/A' ); 